server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://192.168.63.3:7010/test_db"
    username: postgres
    password: postgres
